### ISSUE TITLE
代码运行报错

### ISSUE THREAD

**Issue by zhengwenjun1437** [AONE-NLP/ABSA-AOAN#3]
尝试运行代码，发现有多处错误，例如，模型中的opt.SRD，self.bert_local等没有，data_utils.py中的mask1，mask2，mask3，mask4没有等。期待作者能更新更完整的代码。

**Comment by hodorxxx** [comment]
已更新

**Comment by zhengwenjun1437** [comment]
感动的快哭了，第一次有人回我
