### ISSUE TITLE
模型复现

### ISSUE THREAD

**Issue by liuzh00** [AONE-NLP/ABSA-AOAN#4]
作者您好，我对您的研究很感兴趣，在我复现您模型的过程中，出现了一下问题：1.input_cols中的aspect_boundary好像没有使用  2.根据论文中的超参数进行复现时，结果很难接近论文中的指标，我不知道是我设置的哪里出现问题。期待您的解答，祝您生活愉快，学业进步！
![7{9IVQ)I})MRBW6M8KB$9TO](https://github.com/AONE-NLP/ABSA-AOAN/assets/125945273/6cfb8be4-68fb-427c-9444-8046c82037ab)
![FRGEX2UZTV F$}))RK518J](https://github.com/AONE-NLP/ABSA-AOAN/assets/125945273/05270325-de9c-472c-a8f2-7d86500012a7)

**Comment by hodorxxx** [comment]
您好，aspect_boundary在模型里没有使用，可以从input_cols中删除。您复现的laptop数据集可以参考我们论文中的最优参数threshold=10，另外patience控制模型的早停，也可以将这个参数稍微调大。在我们的实验中发现随机种子也会对小数据集上的实验结果产生比较大的影响，您可以试着多跑几个随机种子。

**Comment by liuzh00** [comment]
非常感谢您的解答，请问您在调参训练过程中，是否经常出现训练loss下降，训练acc上升，验证acc不上升的情况，您在论文中提到使用CLS的表征作为Q，但代码里使用的好像是自注意力机制，是否是因为前者效果不好呢（也许是我理解有问题），另外可以请您提供几个比较可靠的随机种子吗？再次感谢您的解答。

**Comment by hodorxxx** [comment]
训练acc上升验证acc下降是正常现象，模型在对训练集进行拟合的过程中泛化性可能会下降。因为我们在计算loss的时候只用到了CLS，算梯度时只会对CLS的表征进行计算，所以我们使用自注意力机制和注意力机制实现的是相同的效果。我们使用的是代码中的随机种子，在我们的机器上能达到好的效果。

**Comment by liuzh00** [comment]
感谢您的耐心解答。
